### ISSUE TITLE
SharePayload Error on Android 11

### ISSUE THREAD

**Issue by Suneesh-Menon** [natmlx/NatShare#126]
2022-01-25 14:17:19.077 9801-11206/com.venuenext.coyotes E/AndroidRuntime: FATAL EXCEPTION: SharePayload
    Process: .UnityThread, PID: 9801
    java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/com.venuenext.coyotes/cache/78a84821-7465-4ae5-b60a-802b6052187a.jpg
        at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:744)
        at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:418)
        at api.natsuite.natshare.SharePayload.addMedia(SharePayload.java:76)
        at api.natsuite.natshare.SharePayload.lambda$addImage$0$SharePayload(SharePayload.java:67)
        at api.natsuite.natshare.-$$Lambda$SharePayload$SFNI7HZzK-1-FSCX1qHx8U6Tovs.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
        
        
Code:
            var payload = new SharePayload();
            payload.AddImage(texture);
            var success = await payload.Commit();
            //alternatively:
            //payload.Commit();

**Comment by olokobayusuf** [comment]
I'm not able to reproduce this. Can you export your project from Unity (enable the "Export project" option in Build Settings) and share your `AndroidManifest.xml`? Also, can you confirm that your Player Settings looks like this:
<img width="525" alt="Screen Shot 2022-02-06 at 12 17 45 PM" src="https://user-images.githubusercontent.com/17663473/152692592-ecdb59f0-bc13-4133-a782-cb2137b9dd87.png">

**Comment by olokobayusuf** [comment]
Closing because I'm unable to repro, and due to lack of activity.
